import {
  ArrowUp,
  Bot,
  ChevronRight,
  CircleArrowUp,
  Loader,
  LucideIcon,
  MessageCircleMore,
  Puzzle,
  RefreshCw,
  Sparkles,
  SquarePen,
  StopCircle,
  TrendingUp,
} from "lucide-react";

export const Icons = {
  sparkles: Sparkles,
  arrowUp: ArrowUp,
  loader: Loader,
  chevronRight: ChevronRight,
  circleArrowUp: CircleArrowUp,
  stopCircle: StopCircle,
  refreshCw: RefreshCw,
  squarePen: SquarePen,
  bot: Bot,
  messageCircleMore: MessageCircleMore,
  trendingUp: TrendingUp,
  puzzle: Puzzle,
} satisfies Record<string, LucideIcon>;
